name: Test on demand

on:
  workflow_dispatch:
    inputs:
      subset:
        description: 'Which subset of tests to run'
        type: choice
        default: 'basic'
        options:
          - basic
          - data-driven
          - performance
          - visual-comparison

jobs:
  test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Run tests of subset ${{ inputs.subset }}
    environment:
      name: ${{ inputs.subset }}
    runs-on: ${{ matrix.os}}
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Run ${{ inputs.subset }} tests
        continue-on-error: true
        working-directory: ${{ inputs.subset }}
        run: |
          HOME=/root npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.subset }}
          path: playwright-report/
    